"""Retrieval‑Augmented Generation (RAG) engine and memory manager.

This module exposes a single ``RAGEngine`` class that handles document ingestion,
memory tracking and question answering.  The rest of the application simply
needs to create one global instance and call ``query``/``add_memory``; the heavy
lifting is done behind the scenes.
"""

import os
from typing import Optional

from groq import Groq
from pipelines.embeddings import get_embeddings
from retrieval.vector_store import VectorStore


class RAGEngine:
    def __init__(
        self,
        docs_path: str = "knowledge/photon_docs",
        index_path: str = "rag_index.pkl",
        memory_path: str = "memory_index.pkl",
    ):
        self._client = Groq(api_key=os.getenv("GROQ_API_KEY"))
        self.docs_path = docs_path
        self.doc_store = VectorStore(index_path)
        self.mem_store = VectorStore(memory_path)

        # build index lazily; user must explicitly call ``ingest_documents``
        # if they want to (re)index the knowledge base.

    # ---------- ingestion helpers -------------------------------------------
    def ingest_documents(self) -> None:
        """Walk ``self.docs_path`` and index every file it contains."""

        from pipelines.ingestion_pipeline import ingest_directory

        ingest_directory(self.docs_path, self.doc_store.path or "")

    # ---------- memory helpers ----------------------------------------------
    def add_memory(self, text: str) -> None:
        """Remember some piece of text for later retrieval.

        ``text`` is typically a brief summary of a turn of conversation or a
        fact that should not be forgotten.  Internally it is just put through the
        same vector store that holds the documents.
        """

        if not text:
            return
        emb = get_embeddings([text])[0]
        # use length of existing ids as a simple unique key
        self.mem_store.add(id=str(len(self.mem_store.ids)), text=text, embedding=emb)
        self.mem_store.save()

    def retrieve_memory(self, query: str, top_k: int = 3) -> list[dict]:
        """Return ``top_k`` memory entries most relevant to ``query``."""

        return self.mem_store.search(query, top_k)

    # ---------- query interface ---------------------------------------------
    def query(self, question: str, top_k_docs: int = 5, top_k_mem: int = 3) -> str:
        """Answer ``question`` by combining retrieved documents, memory and LLM.

        Returns the text generated by the LLM.  If the index files are empty the
        engine will still try to generate a response, but the behaviour will
        degrade to a plain LLM call.
        """

        # retrieve relevant memories and documents
        docs = self.doc_store.search(question, top_k_docs)
        mems = self.mem_store.search(question, top_k_mem)

        # if neither documents nor memories produced anything worth using we
        # treat the query as "out of domain" and return ``None`` so the caller
        # can fall back to the shipping-only policy.
        if not docs and not mems:
            return None

        # assemble a simple context block
        pieces = []
        if mems:
            pieces.append("\n\n".join([m["text"] for m in mems]))
        if docs:
            pieces.append("\n\n".join([d["text"] for d in docs]))
        context = "\n\n".join(pieces)

        system_prompt = (
            """You are a helpful assistant with access to a collection of internal documents.

When you answer, first read the entire context and draw on all of it; do not limit
yourself to the first matching fragment. Be explicit about sources if they are relevant.
Automatically correct minor typos in the user question (e.g. treat 'EHO' as 'WHO').
Respond in professional, natural language. Do not include any Markdown-style asterisks ("**");
if you need emphasis use ALL CAPS, underlined lines, or plain-text headings such as
"SECTION:" or "-- Section Name --".

Keep sentences short (around 20 words). If the answer would be long, break it into
multiple paragraphs or numbered/bulleted points. For a very short user query (3 or
fewer words) reply in one or two sentences only.

Think like a production‑level knowledge bot: deliver answers in clear, multi‑line format
with headings and bullet points where appropriate. Break complex information into
bullet points or numbered lists. For document summaries, provide a section‑by‑section
overview.

Always conclude with a polite prompt such as 'Anything else I can help with?'."""
        )

        # build the messages payload in the same style as ai_orchestrator
        # if the question is very short, ask the model to keep its response
        # brief (one or two sentences) to avoid verbosity.
        is_short = len(question.split()) <= 3

        user_instr = f"Context:\n{context}\n\nQuestion: {question}\n"
        if is_short:
            user_instr += (
                "\nPlease answer succinctly in one or two sentences. "
                "Do NOT add a long explanation unless asked."
            )
        else:
            user_instr += (
                "\nPlease respond with a comprehensive, well‑formatted answer. "
                "Use multiple lines and bullet points where appropriate."
            )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_instr},
        ]

        response = self._client.chat.completions.create(
            model="llama-3.1-8b-instant",
            temperature=0.2,
            messages=messages,
        )

        answer = response.choices[0].message.content

        # simple heuristic: if the reply is very short or appears to focus on a
        # single table / topic when the user asked a general question, ask for
        # a broader summary.  This helps avoid the "templated shipping table"
        # behaviour noted by the user.
        if (
            len(answer.split()) < 50
            or "Shipment Tracking Table" in answer
            or "shipping" in answer.lower() and len(answer.split("\n")) < 3
        ):
            follow = (
                "The previous answer was too narrow. "
                "Please provide a more comprehensive overview covering all of the "
                "context documents. Use bold headings and bullet points."
            )
            messages.append({"role": "user", "content": follow})
            response2 = self._client.chat.completions.create(
                model="llama-3.1-8b-instant",
                temperature=0.2,
                messages=messages,
            )
            answer = response2.choices[0].message.content

        # strip any asterisks that may have sneaked into the output
        return answer.replace("*", "")


# convenience singleton instance used by ai_orchestrator
rag_engine = RAGEngine()
